import { useState, useMemo } from "react";
import { DashboardCard } from "@/components/shared/dashboard-card";
import { DataTable } from "@/components/shared/data-table";
import type { Column } from "@/components/shared/data-table";
import { StatusBadge } from "@/components/shared/status-badge";
import { Badge } from "@/components/ui/badge";
import {
  Select,
  SelectTrigger,
  SelectValue,
  SelectContent,
  SelectItem,
} from "@/components/ui/select";
import { useAnalyticsStore } from "@/stores/analytics-store";
import { getKpiDefinition } from "@/config/kpi-definitions";
import { Bell } from "lucide-react";
import type { CtaAlert, KpiType } from "@/types";

const SEVERITY_CLASSES: Record<string, string> = {
  critical: "border-status-error text-status-error bg-status-error-bg",
  high: "border-status-warning text-status-warning bg-status-warning-bg",
  medium: "border-status-info text-status-info bg-status-info-bg",
  low: "border-border-default text-text-muted",
};

const columns: Column<CtaAlert>[] = [
  {
    key: "date",
    header: "Date",
    sortable: true,
    sortValue: (row) => row.createdAt,
    cell: (row) =>
      new Date(row.createdAt).toLocaleDateString("en-MY", {
        day: "2-digit",
        month: "short",
        year: "numeric",
      }),
    className: "whitespace-nowrap",
  },
  {
    key: "kpi",
    header: "KPI",
    cell: (row) => (
      <Badge variant="secondary" className="text-[10px]">
        {getKpiDefinition(row.kpiType).shortName}
      </Badge>
    ),
  },
  {
    key: "severity",
    header: "Severity",
    sortable: true,
    sortValue: (row) => {
      const order = { critical: 0, high: 1, medium: 2, low: 3 };
      return order[row.severity];
    },
    cell: (row) => (
      <Badge
        variant="outline"
        className={`text-[10px] font-medium ${SEVERITY_CLASSES[row.severity] ?? ""}`}
      >
        {row.severity}
      </Badge>
    ),
  },
  {
    key: "title",
    header: "Title",
    cell: (row) => (
      <span className="text-sm text-text-primary">{row.title}</span>
    ),
    className: "max-w-[260px] truncate",
  },
  {
    key: "action",
    header: "Action",
    cell: (row) => (
      <span className="text-xs text-text-muted">{row.action}</span>
    ),
    className: "max-w-[240px] truncate",
  },
  {
    key: "status",
    header: "Status",
    sortable: true,
    sortValue: (row) => row.status,
    cell: (row) => <StatusBadge status={row.status} />,
  },
];

export function CtaTriggerLog() {
  const { ctaLog } = useAnalyticsStore();
  const [kpiFilter, setKpiFilter] = useState<string>("all");
  const [severityFilter, setSeverityFilter] = useState<string>("all");
  const [statusFilter, setStatusFilter] = useState<string>("all");

  const filtered = useMemo(() => {
    let result = [...ctaLog].sort(
      (a, b) =>
        new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime(),
    );
    if (kpiFilter !== "all")
      result = result.filter((a) => a.kpiType === kpiFilter);
    if (severityFilter !== "all")
      result = result.filter((a) => a.severity === severityFilter);
    if (statusFilter !== "all")
      result = result.filter((a) => a.status === statusFilter);
    return result;
  }, [ctaLog, kpiFilter, severityFilter, statusFilter]);

  return (
    <DashboardCard
      icon={Bell}
      title="CTA Trigger Log"
      description="All call-to-action alerts generated by the steerage engine"
      badge={`${ctaLog.length} alerts`}
    >
      {/* Filter bar */}
      <div className="mb-4 flex flex-wrap items-center gap-3">
        <Select value={kpiFilter} onValueChange={setKpiFilter}>
          <SelectTrigger className="h-8 w-[150px] text-xs">
            <SelectValue placeholder="KPI Type" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all">All KPIs</SelectItem>
            <SelectItem value={"acceptance_rate" satisfies KpiType}>Acceptance</SelectItem>
            <SelectItem value={"leakage_rate" satisfies KpiType}>Leakage</SelectItem>
            <SelectItem value={"cost_avoidance" satisfies KpiType}>Cost Saved</SelectItem>
            <SelectItem value={"referral_compliance" satisfies KpiType}>Referral Comp.</SelectItem>
            <SelectItem value={"fragmentation_rate" satisfies KpiType}>Fragmentation</SelectItem>
            <SelectItem value={"benefits_utilisation" satisfies KpiType}>Benefits Used</SelectItem>
          </SelectContent>
        </Select>

        <Select value={severityFilter} onValueChange={setSeverityFilter}>
          <SelectTrigger className="h-8 w-[130px] text-xs">
            <SelectValue placeholder="Severity" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all">All Severity</SelectItem>
            <SelectItem value="critical">Critical</SelectItem>
            <SelectItem value="high">High</SelectItem>
            <SelectItem value="medium">Medium</SelectItem>
            <SelectItem value="low">Low</SelectItem>
          </SelectContent>
        </Select>

        <Select value={statusFilter} onValueChange={setStatusFilter}>
          <SelectTrigger className="h-8 w-[130px] text-xs">
            <SelectValue placeholder="Status" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all">All Status</SelectItem>
            <SelectItem value="pending">Pending</SelectItem>
            <SelectItem value="actioned">Actioned</SelectItem>
            <SelectItem value="dismissed">Dismissed</SelectItem>
          </SelectContent>
        </Select>
      </div>

      <DataTable columns={columns} data={filtered} />
    </DashboardCard>
  );
}
