import type { DataImport } from "@/types";

export const MOCK_IMPORTS: DataImport[] = [
  {
    id: "imp-001",
    fileName: "sumitomo_members_2026_q1.csv",
    fileType: "csv",
    dataType: "members",
    status: "live",
    recordCount: 412000,
    errorCount: 0,
    warningCount: 34,
    fieldMappings: [
      { source: "member_id", target: "id", mapped: true },
      { source: "full_name", target: "name", mapped: true },
      { source: "date_of_birth", target: "age", mapped: true },
      { source: "gender_code", target: "gender", mapped: true },
      { source: "plan_code", target: "planType", mapped: true },
      { source: "risk_score", target: "riskTier", mapped: true },
      { source: "icd10_codes", target: "conditions", mapped: true },
      { source: "care_stage", target: "careJourneyStage", mapped: true },
      { source: "annual_spend_rm", target: "annualSpend", mapped: true },
      { source: "projected_spend_rm", target: "projectedSpend", mapped: true },
    ],
    uploadedAt: "2026-03-15T08:30:00Z",
    completedAt: "2026-03-15T09:12:00Z",
  },
  {
    id: "imp-002",
    fileName: "pmcares_panel_providers.xlsx",
    fileType: "xlsx",
    dataType: "providers",
    status: "live",
    recordCount: 1847,
    errorCount: 0,
    warningCount: 12,
    fieldMappings: [
      { source: "Provider ID", target: "id", mapped: true },
      { source: "Provider Name", target: "name", mapped: true },
      { source: "Specialty Code", target: "specialty", mapped: true },
      { source: "Tier Level", target: "tier", mapped: true },
      { source: "City", target: "location.city", mapped: true },
      { source: "State", target: "location.state", mapped: true },
      { source: "Latitude", target: "location.lat", mapped: true },
      { source: "Longitude", target: "location.lng", mapped: true },
      { source: "Panel Status", target: "panelStatus", mapped: true },
      { source: "Cashless Flag", target: "cashless", mapped: true },
    ],
    uploadedAt: "2026-03-10T14:00:00Z",
    completedAt: "2026-03-10T14:22:00Z",
  },
  {
    id: "imp-003",
    fileName: "claims_data_jan_mar_2026.csv",
    fileType: "csv",
    dataType: "claims",
    status: "review",
    recordCount: 89000,
    errorCount: 237,
    warningCount: 1420,
    fieldMappings: [
      { source: "claim_ref", target: "id", mapped: true },
      { source: "member_nric", target: "memberId", mapped: true },
      { source: "provider_code", target: "providerId", mapped: true },
      { source: "claim_amount_rm", target: "amount", mapped: true },
      { source: "icd10_primary", target: "diagnosisCode", mapped: true },
      { source: "procedure_code", target: "procedureCode", mapped: true },
      { source: "claim_date", target: "claimDate", mapped: true },
      { source: "approval_status", target: "status", mapped: true },
      { source: "copay_amount", target: "copayAmount", mapped: false },
      { source: "referring_doc", target: "referringProvider", mapped: false },
    ],
    uploadedAt: "2026-04-10T10:15:00Z",
  },
  {
    id: "imp-004",
    fileName: "panel_assignments_apr_2026.csv",
    fileType: "csv",
    dataType: "panels",
    status: "validating",
    recordCount: 3200,
    errorCount: 0,
    warningCount: 45,
    fieldMappings: [
      { source: "assignment_id", target: "id", mapped: true },
      { source: "provider_id", target: "providerId", mapped: true },
      { source: "plan_code", target: "planType", mapped: true },
      { source: "effective_date", target: "effectiveDate", mapped: true },
      { source: "expiry_date", target: "expiryDate", mapped: true },
      { source: "tier_override", target: "tierOverride", mapped: true },
      { source: "cashless_flag", target: "cashless", mapped: true },
      { source: "region_code", target: "region", mapped: false },
    ],
    uploadedAt: "2026-04-12T16:45:00Z",
  },
  {
    id: "imp-005",
    fileName: "provider_quality_scores_2026.xlsx",
    fileType: "xlsx",
    dataType: "providers",
    status: "failed",
    recordCount: 0,
    errorCount: 1847,
    warningCount: 0,
    fieldMappings: [
      { source: "provider_ref", target: "id", mapped: true },
      { source: "clinical_quality_pct", target: "scores.clinicalQuality", mapped: true },
      { source: "patient_exp_pct", target: "scores.patientExperience", mapped: true },
      { source: "cost_index", target: "scores.cost", mapped: false },
      { source: "access_score", target: "scores.access", mapped: false },
      { source: "network_tier_val", target: "scores.networkTier", mapped: false },
      { source: "utilisation_pct", target: "scores.utilisation", mapped: false },
    ],
    uploadedAt: "2026-04-13T09:00:00Z",
    completedAt: "2026-04-13T09:05:00Z",
  },
];
