import type { Member, SteerageEvent, MemberExclusion } from "@/types";

export const MOCK_MEMBERS: Member[] = [
  // ── Low risk (8) ──
  {
    id: "mem-001",
    name: "Tan Mei Ling",
    age: 32,
    gender: "F",
    planType: "Standard Silver",
    riskTier: "low",
    conditions: ["asthma"],
    careJourneyStage: "follow_up",
    steerageScore: 18,
    overrideCount: 0,
    fragmentationScore: 0.08,
    lastActivity: "2026-04-10T09:30:00Z",
    preferredProviders: ["prov-016"],
    benefitsUsed: 2,
    benefitsTotal: 6,
    annualSpend: 1200,
    projectedSpend: 1800,
    appEngaged: true,
    transactionsOnApp: 5,
    totalTransactions: 7,
  },
  {
    id: "mem-002",
    name: "Ahmad Firdaus bin Osman",
    age: 28,
    gender: "M",
    planType: "Basic Bronze",
    riskTier: "low",
    conditions: [],
    careJourneyStage: "new_episode",
    steerageScore: 12,
    overrideCount: 0,
    fragmentationScore: 0.0,
    lastActivity: "2026-04-08T14:00:00Z",
    preferredProviders: [],
    benefitsUsed: 1,
    benefitsTotal: 4,
    annualSpend: 350,
    projectedSpend: 600,
    appEngaged: true,
    transactionsOnApp: 3,
    totalTransactions: 4,
  },
  {
    id: "mem-003",
    name: "Liew Siew Peng",
    age: 45,
    gender: "F",
    planType: "Standard Silver",
    riskTier: "low",
    conditions: ["hypertension"],
    careJourneyStage: "follow_up",
    steerageScore: 22,
    overrideCount: 1,
    fragmentationScore: 0.12,
    lastActivity: "2026-04-05T10:15:00Z",
    preferredProviders: ["prov-010"],
    benefitsUsed: 3,
    benefitsTotal: 6,
    annualSpend: 2100,
    projectedSpend: 2800,
    appEngaged: true,
    transactionsOnApp: 6,
    totalTransactions: 9,
  },
  {
    id: "mem-004",
    name: "Rajesh a/l Subramaniam",
    age: 38,
    gender: "M",
    planType: "Premium Gold",
    riskTier: "low",
    conditions: [],
    careJourneyStage: "new_episode",
    steerageScore: 10,
    overrideCount: 0,
    fragmentationScore: 0.0,
    lastActivity: "2026-03-28T16:00:00Z",
    preferredProviders: [],
    benefitsUsed: 1,
    benefitsTotal: 8,
    annualSpend: 480,
    projectedSpend: 900,
    appEngaged: false,
    transactionsOnApp: 1,
    totalTransactions: 3,
  },
  {
    id: "mem-005",
    name: "Nurul Izzah binti Ahmad",
    age: 29,
    gender: "F",
    planType: "Basic Bronze",
    riskTier: "low",
    conditions: [],
    careJourneyStage: "new_episode",
    steerageScore: 14,
    overrideCount: 0,
    fragmentationScore: 0.0,
    lastActivity: "2026-04-12T11:00:00Z",
    preferredProviders: [],
    benefitsUsed: 0,
    benefitsTotal: 4,
    annualSpend: 0,
    projectedSpend: 400,
    appEngaged: true,
    transactionsOnApp: 2,
    totalTransactions: 3,
  },
  {
    id: "mem-006",
    name: "Ong Kai Wen",
    age: 41,
    gender: "M",
    planType: "Standard Silver",
    riskTier: "low",
    conditions: ["asthma"],
    careJourneyStage: "follow_up",
    steerageScore: 20,
    overrideCount: 1,
    fragmentationScore: 0.10,
    lastActivity: "2026-04-09T08:45:00Z",
    preferredProviders: ["prov-025"],
    benefitsUsed: 2,
    benefitsTotal: 6,
    annualSpend: 1500,
    projectedSpend: 2200,
    appEngaged: true,
    transactionsOnApp: 4,
    totalTransactions: 6,
  },
  {
    id: "mem-007",
    name: "Shalini a/p Ramachandran",
    age: 25,
    gender: "F",
    planType: "Basic Bronze",
    riskTier: "low",
    conditions: [],
    careJourneyStage: "new_episode",
    steerageScore: 11,
    overrideCount: 0,
    fragmentationScore: 0.0,
    lastActivity: "2026-04-01T13:30:00Z",
    preferredProviders: [],
    benefitsUsed: 1,
    benefitsTotal: 4,
    annualSpend: 250,
    projectedSpend: 500,
    appEngaged: true,
    transactionsOnApp: 3,
    totalTransactions: 4,
  },
  {
    id: "mem-008",
    name: "Chong Wei Keat",
    age: 50,
    gender: "M",
    planType: "Premium Gold",
    riskTier: "low",
    conditions: ["hypertension"],
    careJourneyStage: "follow_up",
    steerageScore: 25,
    overrideCount: 1,
    fragmentationScore: 0.15,
    lastActivity: "2026-04-11T15:20:00Z",
    preferredProviders: ["prov-001"],
    benefitsUsed: 3,
    benefitsTotal: 8,
    annualSpend: 2800,
    projectedSpend: 3500,
    appEngaged: false,
    transactionsOnApp: 3,
    totalTransactions: 8,
  },

  // ── Moderate risk (10) ──
  {
    id: "mem-009",
    name: "Amirah binti Zainal",
    age: 52,
    gender: "F",
    planType: "Standard Silver",
    riskTier: "moderate",
    conditions: ["diabetes", "hypertension"],
    careJourneyStage: "mid_treatment",
    steerageScore: 45,
    overrideCount: 3,
    fragmentationScore: 0.35,
    lastActivity: "2026-04-13T10:00:00Z",
    preferredProviders: ["prov-011", "prov-010"],
    benefitsUsed: 4,
    benefitsTotal: 6,
    annualSpend: 6200,
    projectedSpend: 8500,
    appEngaged: true,
    transactionsOnApp: 8,
    totalTransactions: 14,
  },
  {
    id: "mem-010",
    name: "Lee Chun Hao",
    age: 60,
    gender: "M",
    planType: "Premium Gold",
    riskTier: "moderate",
    conditions: ["cardiac"],
    careJourneyStage: "follow_up",
    steerageScore: 48,
    overrideCount: 4,
    fragmentationScore: 0.40,
    lastActivity: "2026-04-12T09:30:00Z",
    preferredProviders: ["prov-001", "prov-020"],
    benefitsUsed: 5,
    benefitsTotal: 8,
    annualSpend: 9400,
    projectedSpend: 12000,
    appEngaged: false,
    transactionsOnApp: 4,
    totalTransactions: 18,
  },
  {
    id: "mem-011",
    name: "Norhayati binti Md Nor",
    age: 47,
    gender: "F",
    planType: "Standard Silver",
    riskTier: "moderate",
    conditions: ["diabetes"],
    careJourneyStage: "mid_treatment",
    steerageScore: 42,
    overrideCount: 2,
    fragmentationScore: 0.28,
    lastActivity: "2026-04-10T14:45:00Z",
    preferredProviders: ["prov-002"],
    benefitsUsed: 3,
    benefitsTotal: 6,
    annualSpend: 4800,
    projectedSpend: 6200,
    appEngaged: true,
    transactionsOnApp: 7,
    totalTransactions: 12,
  },
  {
    id: "mem-012",
    name: "Govindan a/l Nair",
    age: 55,
    gender: "M",
    planType: "Corporate Platinum",
    riskTier: "moderate",
    conditions: ["hypertension", "diabetes"],
    careJourneyStage: "follow_up",
    steerageScore: 50,
    overrideCount: 3,
    fragmentationScore: 0.38,
    lastActivity: "2026-04-11T11:00:00Z",
    preferredProviders: ["prov-001", "prov-002"],
    benefitsUsed: 6,
    benefitsTotal: 10,
    annualSpend: 8200,
    projectedSpend: 10500,
    appEngaged: false,
    transactionsOnApp: 5,
    totalTransactions: 16,
  },
  {
    id: "mem-013",
    name: "Wong Pei Shan",
    age: 43,
    gender: "F",
    planType: "Standard Silver",
    riskTier: "moderate",
    conditions: ["asthma", "mental health"],
    careJourneyStage: "mid_treatment",
    steerageScore: 40,
    overrideCount: 2,
    fragmentationScore: 0.32,
    lastActivity: "2026-04-09T16:30:00Z",
    preferredProviders: ["prov-016"],
    benefitsUsed: 3,
    benefitsTotal: 6,
    annualSpend: 3900,
    projectedSpend: 5800,
    appEngaged: true,
    transactionsOnApp: 6,
    totalTransactions: 10,
  },
  {
    id: "mem-014",
    name: "Ismail bin Hashim",
    age: 58,
    gender: "M",
    planType: "Premium Gold",
    riskTier: "moderate",
    conditions: ["orthopedic"],
    careJourneyStage: "new_episode",
    steerageScore: 38,
    overrideCount: 2,
    fragmentationScore: 0.22,
    lastActivity: "2026-04-08T09:00:00Z",
    preferredProviders: ["prov-004"],
    benefitsUsed: 2,
    benefitsTotal: 8,
    annualSpend: 3200,
    projectedSpend: 7500,
    appEngaged: false,
    transactionsOnApp: 2,
    totalTransactions: 8,
  },
  {
    id: "mem-015",
    name: "Yap Sook Yee",
    age: 49,
    gender: "F",
    planType: "Standard Silver",
    riskTier: "moderate",
    conditions: ["diabetes"],
    careJourneyStage: "follow_up",
    steerageScore: 44,
    overrideCount: 3,
    fragmentationScore: 0.30,
    lastActivity: "2026-04-07T13:15:00Z",
    preferredProviders: ["prov-023"],
    benefitsUsed: 4,
    benefitsTotal: 6,
    annualSpend: 5100,
    projectedSpend: 6800,
    appEngaged: false,
    transactionsOnApp: 4,
    totalTransactions: 11,
  },
  {
    id: "mem-016",
    name: "Mohd Rizal bin Abdullah",
    age: 44,
    gender: "M",
    planType: "Corporate Platinum",
    riskTier: "moderate",
    conditions: ["hypertension"],
    careJourneyStage: "mid_treatment",
    steerageScore: 36,
    overrideCount: 1,
    fragmentationScore: 0.18,
    lastActivity: "2026-04-13T08:30:00Z",
    preferredProviders: ["prov-001"],
    benefitsUsed: 4,
    benefitsTotal: 10,
    annualSpend: 4500,
    projectedSpend: 5600,
    appEngaged: true,
    transactionsOnApp: 8,
    totalTransactions: 12,
  },
  {
    id: "mem-017",
    name: "Saravanan a/l Muniandy",
    age: 62,
    gender: "M",
    planType: "Premium Gold",
    riskTier: "moderate",
    conditions: ["COPD"],
    careJourneyStage: "follow_up",
    steerageScore: 46,
    overrideCount: 4,
    fragmentationScore: 0.36,
    lastActivity: "2026-04-06T10:00:00Z",
    preferredProviders: ["prov-006", "prov-025"],
    benefitsUsed: 5,
    benefitsTotal: 8,
    annualSpend: 7300,
    projectedSpend: 9200,
    appEngaged: false,
    transactionsOnApp: 3,
    totalTransactions: 15,
  },
  {
    id: "mem-018",
    name: "Nur Ain binti Kamal",
    age: 35,
    gender: "F",
    planType: "Standard Silver",
    riskTier: "moderate",
    conditions: ["mental health"],
    careJourneyStage: "mid_treatment",
    steerageScore: 34,
    overrideCount: 2,
    fragmentationScore: 0.20,
    lastActivity: "2026-04-12T15:00:00Z",
    preferredProviders: ["prov-009"],
    benefitsUsed: 3,
    benefitsTotal: 6,
    annualSpend: 3400,
    projectedSpend: 5000,
    appEngaged: true,
    transactionsOnApp: 5,
    totalTransactions: 7,
  },

  // ── High risk (8) ──
  {
    id: "mem-019",
    name: "Lim Ah Kow",
    age: 67,
    gender: "M",
    planType: "Premium Gold",
    riskTier: "high",
    conditions: ["cardiac", "diabetes", "hypertension"],
    careJourneyStage: "mid_treatment",
    steerageScore: 72,
    overrideCount: 7,
    fragmentationScore: 0.62,
    lastActivity: "2026-04-13T11:45:00Z",
    preferredProviders: ["prov-001", "prov-020", "prov-002"],
    benefitsUsed: 6,
    benefitsTotal: 8,
    annualSpend: 18500,
    projectedSpend: 24000,
    appEngaged: false,
    transactionsOnApp: 3,
    totalTransactions: 22,
  },
  {
    id: "mem-020",
    name: "Fatimah binti Yusof",
    age: 59,
    gender: "F",
    planType: "Corporate Platinum",
    riskTier: "high",
    conditions: ["cancer", "hypertension"],
    careJourneyStage: "mid_treatment",
    steerageScore: 68,
    overrideCount: 5,
    fragmentationScore: 0.55,
    lastActivity: "2026-04-14T08:00:00Z",
    preferredProviders: ["prov-003", "prov-018"],
    benefitsUsed: 8,
    benefitsTotal: 10,
    annualSpend: 32000,
    projectedSpend: 42000,
    appEngaged: true,
    transactionsOnApp: 12,
    totalTransactions: 20,
  },
  {
    id: "mem-021",
    name: "Ng Kok Leong",
    age: 63,
    gender: "M",
    planType: "Premium Gold",
    riskTier: "high",
    conditions: ["cardiac", "COPD"],
    careJourneyStage: "follow_up",
    steerageScore: 70,
    overrideCount: 6,
    fragmentationScore: 0.58,
    lastActivity: "2026-04-11T09:30:00Z",
    preferredProviders: ["prov-001", "prov-006"],
    benefitsUsed: 7,
    benefitsTotal: 8,
    annualSpend: 15600,
    projectedSpend: 20000,
    appEngaged: false,
    transactionsOnApp: 4,
    totalTransactions: 19,
  },
  {
    id: "mem-022",
    name: "Rohana binti Zakaria",
    age: 56,
    gender: "F",
    planType: "Standard Silver",
    riskTier: "high",
    conditions: ["diabetes", "orthopedic"],
    careJourneyStage: "mid_treatment",
    steerageScore: 65,
    overrideCount: 5,
    fragmentationScore: 0.52,
    lastActivity: "2026-04-10T14:00:00Z",
    preferredProviders: ["prov-002", "prov-014"],
    benefitsUsed: 5,
    benefitsTotal: 6,
    annualSpend: 11200,
    projectedSpend: 14800,
    appEngaged: false,
    transactionsOnApp: 3,
    totalTransactions: 15,
  },
  {
    id: "mem-023",
    name: "Krishnan a/l Pillai",
    age: 70,
    gender: "M",
    planType: "Premium Gold",
    riskTier: "high",
    conditions: ["cardiac", "diabetes"],
    careJourneyStage: "follow_up",
    steerageScore: 74,
    overrideCount: 8,
    fragmentationScore: 0.65,
    lastActivity: "2026-04-09T10:30:00Z",
    preferredProviders: ["prov-001", "prov-010"],
    benefitsUsed: 7,
    benefitsTotal: 8,
    annualSpend: 21000,
    projectedSpend: 27500,
    appEngaged: false,
    transactionsOnApp: 2,
    totalTransactions: 20,
  },
  {
    id: "mem-024",
    name: "Tan Bee Lan",
    age: 54,
    gender: "F",
    planType: "Corporate Platinum",
    riskTier: "high",
    conditions: ["cancer"],
    careJourneyStage: "mid_treatment",
    steerageScore: 66,
    overrideCount: 4,
    fragmentationScore: 0.48,
    lastActivity: "2026-04-13T16:00:00Z",
    preferredProviders: ["prov-003"],
    benefitsUsed: 9,
    benefitsTotal: 10,
    annualSpend: 38000,
    projectedSpend: 48000,
    appEngaged: true,
    transactionsOnApp: 10,
    totalTransactions: 18,
  },
  {
    id: "mem-025",
    name: "Azizul bin Razak",
    age: 61,
    gender: "M",
    planType: "Standard Silver",
    riskTier: "high",
    conditions: ["hypertension", "COPD", "diabetes"],
    careJourneyStage: "mid_treatment",
    steerageScore: 76,
    overrideCount: 9,
    fragmentationScore: 0.70,
    lastActivity: "2026-04-08T11:00:00Z",
    preferredProviders: ["prov-006", "prov-011", "prov-025"],
    benefitsUsed: 5,
    benefitsTotal: 6,
    annualSpend: 14200,
    projectedSpend: 19000,
    appEngaged: false,
    transactionsOnApp: 2,
    totalTransactions: 17,
  },
  {
    id: "mem-026",
    name: "Chew Mei Fong",
    age: 48,
    gender: "F",
    planType: "Premium Gold",
    riskTier: "high",
    conditions: ["cardiac", "mental health"],
    careJourneyStage: "mid_treatment",
    steerageScore: 62,
    overrideCount: 5,
    fragmentationScore: 0.50,
    lastActivity: "2026-04-07T09:00:00Z",
    preferredProviders: ["prov-001", "prov-009"],
    benefitsUsed: 4,
    benefitsTotal: 8,
    annualSpend: 12800,
    projectedSpend: 16500,
    appEngaged: false,
    transactionsOnApp: 3,
    totalTransactions: 14,
  },

  // ── Critical risk (4) ──
  {
    id: "mem-027",
    name: "Datuk Hj. Mohamad Noor",
    age: 72,
    gender: "M",
    planType: "Corporate Platinum",
    riskTier: "critical",
    conditions: ["cardiac", "diabetes", "hypertension", "COPD"],
    careJourneyStage: "mid_treatment",
    steerageScore: 92,
    overrideCount: 12,
    fragmentationScore: 0.85,
    lastActivity: "2026-04-14T07:30:00Z",
    preferredProviders: ["prov-001", "prov-002", "prov-006", "prov-020"],
    benefitsUsed: 9,
    benefitsTotal: 10,
    annualSpend: 45000,
    projectedSpend: 62000,
    appEngaged: false,
    transactionsOnApp: 3,
    totalTransactions: 25,
  },
  {
    id: "mem-028",
    name: "Chia Siew Hong",
    age: 68,
    gender: "F",
    planType: "Premium Gold",
    riskTier: "critical",
    conditions: ["cancer", "cardiac", "diabetes"],
    careJourneyStage: "mid_treatment",
    steerageScore: 88,
    overrideCount: 10,
    fragmentationScore: 0.82,
    lastActivity: "2026-04-13T14:00:00Z",
    preferredProviders: ["prov-003", "prov-001", "prov-002"],
    benefitsUsed: 7,
    benefitsTotal: 8,
    annualSpend: 52000,
    projectedSpend: 68000,
    appEngaged: true,
    transactionsOnApp: 13,
    totalTransactions: 23,
  },
  {
    id: "mem-029",
    name: "Karupaiah a/l Thangavelu",
    age: 75,
    gender: "M",
    planType: "Premium Gold",
    riskTier: "critical",
    conditions: ["cardiac", "COPD", "orthopedic"],
    careJourneyStage: "follow_up",
    steerageScore: 85,
    overrideCount: 11,
    fragmentationScore: 0.78,
    lastActivity: "2026-04-12T10:00:00Z",
    preferredProviders: ["prov-001", "prov-004", "prov-006"],
    benefitsUsed: 8,
    benefitsTotal: 8,
    annualSpend: 38000,
    projectedSpend: 50000,
    appEngaged: false,
    transactionsOnApp: 4,
    totalTransactions: 22,
  },
  {
    id: "mem-030",
    name: "Siti Mariam binti Ismail",
    age: 65,
    gender: "F",
    planType: "Corporate Platinum",
    riskTier: "critical",
    conditions: ["cancer", "hypertension", "mental health"],
    careJourneyStage: "mid_treatment",
    steerageScore: 95,
    overrideCount: 8,
    fragmentationScore: 0.90,
    lastActivity: "2026-04-14T09:00:00Z",
    preferredProviders: ["prov-003", "prov-005", "prov-018"],
    benefitsUsed: 10,
    benefitsTotal: 10,
    annualSpend: 58000,
    projectedSpend: 75000,
    appEngaged: false,
    transactionsOnApp: 2,
    totalTransactions: 21,
  },
];

// ── Steerage Events (100+) ──

export const MOCK_STEERAGE_EVENTS: SteerageEvent[] = [
  // mem-009 — Amirah (moderate, diabetes+hypertension) — 5 events
  { id: "evt-001", memberId: "mem-009", timestamp: "2026-04-12T10:15:00Z", type: "recommendation", providerRecommended: "Dr. Lim Wei Ling", interventionType: "pre_booking", notes: "Endocrinology recommendation for diabetes management" },
  { id: "evt-002", memberId: "mem-009", timestamp: "2026-04-12T10:22:00Z", type: "acceptance", providerRecommended: "Dr. Lim Wei Ling", providerChosen: "Dr. Lim Wei Ling", costDifferential: 0, interventionType: "pre_booking" },
  { id: "evt-003", memberId: "mem-009", timestamp: "2026-04-05T14:00:00Z", type: "recommendation", providerRecommended: "Dr. Ahmad Razak", interventionType: "cost_comparison", notes: "Cardiology referral for hypertension" },
  { id: "evt-004", memberId: "mem-009", timestamp: "2026-04-05T14:10:00Z", type: "override", providerRecommended: "Dr. Ahmad Razak", providerChosen: "Dr. Chong Mei Fong", costDifferential: -600, interventionType: "cost_comparison", notes: "Preferred Ipoh provider due to proximity" },
  { id: "evt-005", memberId: "mem-009", timestamp: "2026-03-20T09:30:00Z", type: "navigator_call", notes: "Care navigator discussed diabetes care plan consolidation" },

  // mem-010 — Lee Chun Hao (moderate, cardiac) — 6 events
  { id: "evt-006", memberId: "mem-010", timestamp: "2026-04-11T08:30:00Z", type: "recommendation", providerRecommended: "Dr. Ahmad Razak", interventionType: "pre_booking", notes: "Cardiac follow-up" },
  { id: "evt-007", memberId: "mem-010", timestamp: "2026-04-11T08:45:00Z", type: "override", providerRecommended: "Dr. Ahmad Razak", providerChosen: "Dr. Chen Wei Ming", costDifferential: -1100, interventionType: "pre_booking", notes: "Long-standing relationship with Dr. Chen" },
  { id: "evt-008", memberId: "mem-010", timestamp: "2026-03-28T11:00:00Z", type: "recommendation", providerRecommended: "Dr. Ahmad Razak", interventionType: "cost_comparison" },
  { id: "evt-009", memberId: "mem-010", timestamp: "2026-03-28T11:15:00Z", type: "dismissal", providerRecommended: "Dr. Ahmad Razak", interventionType: "cost_comparison", notes: "Patient dismissed — prefers Ipoh" },
  { id: "evt-010", memberId: "mem-010", timestamp: "2026-03-15T14:00:00Z", type: "override", providerRecommended: "Dr. Ahmad Razak", providerChosen: "Dr. Chen Wei Ming", costDifferential: -1100, interventionType: "leakage_prevention" },
  { id: "evt-011", memberId: "mem-010", timestamp: "2026-03-10T09:00:00Z", type: "escalation", notes: "Escalated to care manager — repeated overrides for cardiac care" },

  // mem-011 — Norhayati (moderate, diabetes) — 4 events
  { id: "evt-012", memberId: "mem-011", timestamp: "2026-04-09T09:00:00Z", type: "recommendation", providerRecommended: "Dr. Lim Wei Ling", interventionType: "pre_booking" },
  { id: "evt-013", memberId: "mem-011", timestamp: "2026-04-09T09:12:00Z", type: "acceptance", providerRecommended: "Dr. Lim Wei Ling", providerChosen: "Dr. Lim Wei Ling", costDifferential: 0, interventionType: "pre_booking" },
  { id: "evt-014", memberId: "mem-011", timestamp: "2026-03-25T10:30:00Z", type: "recommendation", providerRecommended: "Dr. Lim Wei Ling", interventionType: "follow_up_compliance" },
  { id: "evt-015", memberId: "mem-011", timestamp: "2026-03-25T16:00:00Z", type: "acceptance", providerRecommended: "Dr. Lim Wei Ling", providerChosen: "Dr. Lim Wei Ling", costDifferential: 0, interventionType: "follow_up_compliance" },

  // mem-012 — Govindan (moderate, hypertension+diabetes) — 5 events
  { id: "evt-016", memberId: "mem-012", timestamp: "2026-04-10T11:00:00Z", type: "recommendation", providerRecommended: "Dr. Ahmad Razak", interventionType: "cost_comparison" },
  { id: "evt-017", memberId: "mem-012", timestamp: "2026-04-10T11:20:00Z", type: "acceptance", providerRecommended: "Dr. Ahmad Razak", providerChosen: "Dr. Ahmad Razak", costDifferential: 0, interventionType: "cost_comparison" },
  { id: "evt-018", memberId: "mem-012", timestamp: "2026-03-30T14:30:00Z", type: "recommendation", providerRecommended: "Dr. Lim Wei Ling", interventionType: "pre_booking" },
  { id: "evt-019", memberId: "mem-012", timestamp: "2026-03-30T15:00:00Z", type: "override", providerRecommended: "Dr. Lim Wei Ling", providerChosen: "Dr. Ganesh Kumar", costDifferential: -300, interventionType: "pre_booking", notes: "Prefers Melaka-based provider" },
  { id: "evt-020", memberId: "mem-012", timestamp: "2026-03-18T09:00:00Z", type: "navigator_call", notes: "Discussed combined diabetes-hypertension care plan" },

  // mem-019 — Lim Ah Kow (high, cardiac+diabetes+hypertension) — 8 events
  { id: "evt-021", memberId: "mem-019", timestamp: "2026-04-13T09:00:00Z", type: "recommendation", providerRecommended: "Dr. Ahmad Razak", interventionType: "pre_booking" },
  { id: "evt-022", memberId: "mem-019", timestamp: "2026-04-13T09:30:00Z", type: "override", providerRecommended: "Dr. Ahmad Razak", providerChosen: "Dr. Chen Wei Ming", costDifferential: -1100, interventionType: "pre_booking", notes: "Insists on Dr. Chen" },
  { id: "evt-023", memberId: "mem-019", timestamp: "2026-04-07T10:00:00Z", type: "recommendation", providerRecommended: "Dr. Lim Wei Ling", interventionType: "cost_comparison" },
  { id: "evt-024", memberId: "mem-019", timestamp: "2026-04-07T10:15:00Z", type: "override", providerRecommended: "Dr. Lim Wei Ling", providerChosen: "Dr. Yap Kok Seng", costDifferential: -400, interventionType: "cost_comparison" },
  { id: "evt-025", memberId: "mem-019", timestamp: "2026-03-28T11:00:00Z", type: "escalation", notes: "Escalated — 7 overrides in 30 days, fragmenting cardiac/diabetes care" },
  { id: "evt-026", memberId: "mem-019", timestamp: "2026-03-22T14:00:00Z", type: "navigator_call", notes: "Navigator reviewed care plan — patient resistant to consolidation" },
  { id: "evt-027", memberId: "mem-019", timestamp: "2026-03-15T08:30:00Z", type: "recommendation", providerRecommended: "Dr. Ahmad Razak", interventionType: "leakage_prevention" },
  { id: "evt-028", memberId: "mem-019", timestamp: "2026-03-15T09:00:00Z", type: "dismissal", providerRecommended: "Dr. Ahmad Razak", interventionType: "leakage_prevention", notes: "Patient prefers non-panel provider" },

  // mem-020 — Fatimah (high, cancer+hypertension) — 7 events
  { id: "evt-029", memberId: "mem-020", timestamp: "2026-04-13T10:00:00Z", type: "recommendation", providerRecommended: "Dr. Priya Nair", interventionType: "pre_booking" },
  { id: "evt-030", memberId: "mem-020", timestamp: "2026-04-13T10:08:00Z", type: "acceptance", providerRecommended: "Dr. Priya Nair", providerChosen: "Dr. Priya Nair", costDifferential: 0, interventionType: "pre_booking" },
  { id: "evt-031", memberId: "mem-020", timestamp: "2026-04-05T09:30:00Z", type: "recommendation", providerRecommended: "Dr. Ahmad Razak", interventionType: "cost_comparison", notes: "Hypertension follow-up" },
  { id: "evt-032", memberId: "mem-020", timestamp: "2026-04-05T10:00:00Z", type: "acceptance", providerRecommended: "Dr. Ahmad Razak", providerChosen: "Dr. Ahmad Razak", costDifferential: 0, interventionType: "cost_comparison" },
  { id: "evt-033", memberId: "mem-020", timestamp: "2026-03-25T11:00:00Z", type: "override", providerRecommended: "Dr. Priya Nair", providerChosen: "Dr. Tan Soo Lin", costDifferential: -600, interventionType: "pre_booking", notes: "Preferred Penang oncologist" },
  { id: "evt-034", memberId: "mem-020", timestamp: "2026-03-18T14:00:00Z", type: "navigator_call", notes: "Navigator coordinated oncology treatment plan with hypertension management" },
  { id: "evt-035", memberId: "mem-020", timestamp: "2026-03-10T10:00:00Z", type: "escalation", notes: "Escalated — oncology care fragmentation risk" },

  // mem-021 — Ng Kok Leong (high, cardiac+COPD) — 6 events
  { id: "evt-036", memberId: "mem-021", timestamp: "2026-04-10T08:00:00Z", type: "recommendation", providerRecommended: "Dr. Rajan Krishnan", interventionType: "follow_up_compliance" },
  { id: "evt-037", memberId: "mem-021", timestamp: "2026-04-10T08:20:00Z", type: "acceptance", providerRecommended: "Dr. Rajan Krishnan", providerChosen: "Dr. Rajan Krishnan", costDifferential: 0, interventionType: "follow_up_compliance" },
  { id: "evt-038", memberId: "mem-021", timestamp: "2026-03-30T09:00:00Z", type: "recommendation", providerRecommended: "Dr. Ahmad Razak", interventionType: "pre_booking" },
  { id: "evt-039", memberId: "mem-021", timestamp: "2026-03-30T09:30:00Z", type: "override", providerRecommended: "Dr. Ahmad Razak", providerChosen: "Dr. Chong Mei Fong", costDifferential: -600, interventionType: "pre_booking" },
  { id: "evt-040", memberId: "mem-021", timestamp: "2026-03-20T11:00:00Z", type: "override", providerRecommended: "Dr. Rajan Krishnan", providerChosen: "Dr. Harith Iskandar", costDifferential: -500, interventionType: "cost_comparison" },
  { id: "evt-041", memberId: "mem-021", timestamp: "2026-03-12T14:30:00Z", type: "navigator_call", notes: "Discussed cardiac-COPD coordination with care navigator" },

  // mem-023 — Krishnan (high, cardiac+diabetes) — 8 events
  { id: "evt-042", memberId: "mem-023", timestamp: "2026-04-09T08:00:00Z", type: "recommendation", providerRecommended: "Dr. Ahmad Razak", interventionType: "pre_booking" },
  { id: "evt-043", memberId: "mem-023", timestamp: "2026-04-09T08:20:00Z", type: "override", providerRecommended: "Dr. Ahmad Razak", providerChosen: "Dr. Chong Mei Fong", costDifferential: -600, interventionType: "pre_booking" },
  { id: "evt-044", memberId: "mem-023", timestamp: "2026-04-02T10:00:00Z", type: "recommendation", providerRecommended: "Dr. Lim Wei Ling", interventionType: "cost_comparison" },
  { id: "evt-045", memberId: "mem-023", timestamp: "2026-04-02T10:30:00Z", type: "dismissal", providerRecommended: "Dr. Lim Wei Ling", interventionType: "cost_comparison", notes: "Patient prefers current provider" },
  { id: "evt-046", memberId: "mem-023", timestamp: "2026-03-25T09:00:00Z", type: "override", providerRecommended: "Dr. Ahmad Razak", providerChosen: "Dr. Chen Wei Ming", costDifferential: -1100, interventionType: "leakage_prevention" },
  { id: "evt-047", memberId: "mem-023", timestamp: "2026-03-18T11:00:00Z", type: "escalation", notes: "Escalated — 8 overrides, care fragmentation score 0.65" },
  { id: "evt-048", memberId: "mem-023", timestamp: "2026-03-12T08:00:00Z", type: "navigator_call", notes: "Navigator outreach — patient acknowledges fragmentation but prefers familiar providers" },
  { id: "evt-049", memberId: "mem-023", timestamp: "2026-03-05T14:00:00Z", type: "override", providerRecommended: "Dr. Lim Wei Ling", providerChosen: "Dr. Yap Kok Seng", costDifferential: -400, interventionType: "cost_comparison" },

  // mem-027 — Datuk Mohamad Noor (critical) — 10 events
  { id: "evt-050", memberId: "mem-027", timestamp: "2026-04-14T07:00:00Z", type: "recommendation", providerRecommended: "Dr. Ahmad Razak", interventionType: "pre_booking" },
  { id: "evt-051", memberId: "mem-027", timestamp: "2026-04-14T07:20:00Z", type: "override", providerRecommended: "Dr. Ahmad Razak", providerChosen: "Dr. Chen Wei Ming", costDifferential: -1100, interventionType: "pre_booking" },
  { id: "evt-052", memberId: "mem-027", timestamp: "2026-04-08T09:00:00Z", type: "recommendation", providerRecommended: "Dr. Lim Wei Ling", interventionType: "cost_comparison" },
  { id: "evt-053", memberId: "mem-027", timestamp: "2026-04-08T09:30:00Z", type: "override", providerRecommended: "Dr. Lim Wei Ling", providerChosen: "Dr. Ganesh Kumar", costDifferential: -300, interventionType: "cost_comparison" },
  { id: "evt-054", memberId: "mem-027", timestamp: "2026-04-02T10:00:00Z", type: "recommendation", providerRecommended: "Dr. Rajan Krishnan", interventionType: "follow_up_compliance" },
  { id: "evt-055", memberId: "mem-027", timestamp: "2026-04-02T10:20:00Z", type: "dismissal", providerRecommended: "Dr. Rajan Krishnan", interventionType: "follow_up_compliance", notes: "Patient already has appointment with preferred provider" },
  { id: "evt-056", memberId: "mem-027", timestamp: "2026-03-28T11:00:00Z", type: "escalation", notes: "Critical escalation — 12 overrides, fragmentation 0.85, 4 concurrent conditions" },
  { id: "evt-057", memberId: "mem-027", timestamp: "2026-03-22T08:00:00Z", type: "navigator_call", notes: "Senior navigator assigned — comprehensive care plan review" },
  { id: "evt-058", memberId: "mem-027", timestamp: "2026-03-15T14:00:00Z", type: "override", providerRecommended: "Dr. Ahmad Razak", providerChosen: "Dr. Chen Wei Ming", costDifferential: -1100, interventionType: "leakage_prevention" },
  { id: "evt-059", memberId: "mem-027", timestamp: "2026-03-08T09:30:00Z", type: "override", providerRecommended: "Dr. Rajan Krishnan", providerChosen: "Dr. Harith Iskandar", costDifferential: -500, interventionType: "pre_booking" },

  // mem-028 — Chia Siew Hong (critical, cancer+cardiac+diabetes) — 8 events
  { id: "evt-060", memberId: "mem-028", timestamp: "2026-04-12T10:00:00Z", type: "recommendation", providerRecommended: "Dr. Priya Nair", interventionType: "pre_booking" },
  { id: "evt-061", memberId: "mem-028", timestamp: "2026-04-12T10:10:00Z", type: "acceptance", providerRecommended: "Dr. Priya Nair", providerChosen: "Dr. Priya Nair", costDifferential: 0, interventionType: "pre_booking" },
  { id: "evt-062", memberId: "mem-028", timestamp: "2026-04-05T08:00:00Z", type: "recommendation", providerRecommended: "Dr. Ahmad Razak", interventionType: "cost_comparison" },
  { id: "evt-063", memberId: "mem-028", timestamp: "2026-04-05T08:30:00Z", type: "override", providerRecommended: "Dr. Ahmad Razak", providerChosen: "Dr. Chong Mei Fong", costDifferential: -600, interventionType: "cost_comparison" },
  { id: "evt-064", memberId: "mem-028", timestamp: "2026-03-28T09:00:00Z", type: "override", providerRecommended: "Dr. Lim Wei Ling", providerChosen: "Dr. Yap Kok Seng", costDifferential: -400, interventionType: "pre_booking" },
  { id: "evt-065", memberId: "mem-028", timestamp: "2026-03-22T14:00:00Z", type: "escalation", notes: "Critical — oncology + cardiac + diabetes care across 5 providers" },
  { id: "evt-066", memberId: "mem-028", timestamp: "2026-03-16T10:00:00Z", type: "navigator_call", notes: "Navigator coordinating multi-specialty care plan" },
  { id: "evt-067", memberId: "mem-028", timestamp: "2026-03-08T08:00:00Z", type: "navigator_call", notes: "Initial navigator contact — care plan assessment" },

  // mem-029 — Karupaiah (critical, cardiac+COPD+orthopedic) — 7 events
  { id: "evt-068", memberId: "mem-029", timestamp: "2026-04-11T09:00:00Z", type: "recommendation", providerRecommended: "Dr. Tan Chee Keong", interventionType: "pre_booking" },
  { id: "evt-069", memberId: "mem-029", timestamp: "2026-04-11T09:15:00Z", type: "acceptance", providerRecommended: "Dr. Tan Chee Keong", providerChosen: "Dr. Tan Chee Keong", costDifferential: 0, interventionType: "pre_booking" },
  { id: "evt-070", memberId: "mem-029", timestamp: "2026-04-04T10:00:00Z", type: "recommendation", providerRecommended: "Dr. Rajan Krishnan", interventionType: "follow_up_compliance" },
  { id: "evt-071", memberId: "mem-029", timestamp: "2026-04-04T10:30:00Z", type: "override", providerRecommended: "Dr. Rajan Krishnan", providerChosen: "Dr. Ong Boon Huat", costDifferential: -200, interventionType: "follow_up_compliance" },
  { id: "evt-072", memberId: "mem-029", timestamp: "2026-03-25T08:00:00Z", type: "override", providerRecommended: "Dr. Ahmad Razak", providerChosen: "Dr. Chen Wei Ming", costDifferential: -1100, interventionType: "leakage_prevention" },
  { id: "evt-073", memberId: "mem-029", timestamp: "2026-03-18T11:00:00Z", type: "escalation", notes: "Escalated — triple-condition patient with high override rate" },
  { id: "evt-074", memberId: "mem-029", timestamp: "2026-03-10T09:00:00Z", type: "navigator_call", notes: "Navigator discussed orthopedic pathway with cardiac clearance" },

  // mem-030 — Siti Mariam (critical, cancer+hypertension+mental health) — 8 events
  { id: "evt-075", memberId: "mem-030", timestamp: "2026-04-14T08:00:00Z", type: "recommendation", providerRecommended: "Dr. Priya Nair", interventionType: "pre_booking" },
  { id: "evt-076", memberId: "mem-030", timestamp: "2026-04-14T08:15:00Z", type: "override", providerRecommended: "Dr. Priya Nair", providerChosen: "Dr. Tan Soo Lin", costDifferential: -600, interventionType: "pre_booking", notes: "Prefers Penang for family support" },
  { id: "evt-077", memberId: "mem-030", timestamp: "2026-04-07T10:00:00Z", type: "recommendation", providerRecommended: "Dr. Farah Aminah", interventionType: "fragmentation_alert" },
  { id: "evt-078", memberId: "mem-030", timestamp: "2026-04-07T10:30:00Z", type: "acceptance", providerRecommended: "Dr. Farah Aminah", providerChosen: "Dr. Farah Aminah", costDifferential: 0, interventionType: "fragmentation_alert" },
  { id: "evt-079", memberId: "mem-030", timestamp: "2026-03-30T09:00:00Z", type: "override", providerRecommended: "Dr. Priya Nair", providerChosen: "Dr. Tan Soo Lin", costDifferential: -600, interventionType: "cost_comparison" },
  { id: "evt-080", memberId: "mem-030", timestamp: "2026-03-24T11:00:00Z", type: "escalation", notes: "Critical — mental health + cancer care coordination breakdown" },
  { id: "evt-081", memberId: "mem-030", timestamp: "2026-03-18T14:00:00Z", type: "navigator_call", notes: "Senior navigator — mental health support + oncology coordination" },
  { id: "evt-082", memberId: "mem-030", timestamp: "2026-03-10T08:30:00Z", type: "navigator_call", notes: "Initial assessment — high distress, multiple active treatments" },

  // mem-022 — Rohana (high, diabetes+orthopedic) — 5 events
  { id: "evt-083", memberId: "mem-022", timestamp: "2026-04-09T14:00:00Z", type: "recommendation", providerRecommended: "Dr. Tan Chee Keong", interventionType: "cost_comparison" },
  { id: "evt-084", memberId: "mem-022", timestamp: "2026-04-09T14:20:00Z", type: "override", providerRecommended: "Dr. Tan Chee Keong", providerChosen: "Dr. Azman Shah", costDifferential: -400, interventionType: "cost_comparison", notes: "Prefers Shah Alam — closer to home" },
  { id: "evt-085", memberId: "mem-022", timestamp: "2026-03-30T10:00:00Z", type: "recommendation", providerRecommended: "Dr. Lim Wei Ling", interventionType: "follow_up_compliance" },
  { id: "evt-086", memberId: "mem-022", timestamp: "2026-03-30T10:15:00Z", type: "acceptance", providerRecommended: "Dr. Lim Wei Ling", providerChosen: "Dr. Lim Wei Ling", costDifferential: 0, interventionType: "follow_up_compliance" },
  { id: "evt-087", memberId: "mem-022", timestamp: "2026-03-20T08:30:00Z", type: "navigator_call", notes: "Navigator discussed diabetes-orthopedic coordination" },

  // mem-025 — Azizul (high, hypertension+COPD+diabetes) — 7 events
  { id: "evt-088", memberId: "mem-025", timestamp: "2026-04-08T08:00:00Z", type: "recommendation", providerRecommended: "Dr. Rajan Krishnan", interventionType: "pre_booking" },
  { id: "evt-089", memberId: "mem-025", timestamp: "2026-04-08T08:30:00Z", type: "override", providerRecommended: "Dr. Rajan Krishnan", providerChosen: "Dr. Harith Iskandar", costDifferential: -500, interventionType: "pre_booking" },
  { id: "evt-090", memberId: "mem-025", timestamp: "2026-04-01T09:00:00Z", type: "recommendation", providerRecommended: "Dr. Lim Wei Ling", interventionType: "cost_comparison" },
  { id: "evt-091", memberId: "mem-025", timestamp: "2026-04-01T09:20:00Z", type: "override", providerRecommended: "Dr. Lim Wei Ling", providerChosen: "Dr. Ganesh Kumar", costDifferential: -300, interventionType: "cost_comparison" },
  { id: "evt-092", memberId: "mem-025", timestamp: "2026-03-25T10:00:00Z", type: "escalation", notes: "Escalated — triple condition, 9 overrides in 60 days" },
  { id: "evt-093", memberId: "mem-025", timestamp: "2026-03-18T14:30:00Z", type: "navigator_call", notes: "Navigator outreach — discussed COPD management consolidation" },
  { id: "evt-094", memberId: "mem-025", timestamp: "2026-03-10T09:00:00Z", type: "dismissal", providerRecommended: "Dr. Ahmad Razak", interventionType: "leakage_prevention", notes: "Patient dismissed — prefers current providers" },

  // mem-013 — Wong Pei Shan (moderate, asthma+mental health) — 4 events
  { id: "evt-095", memberId: "mem-013", timestamp: "2026-04-08T15:00:00Z", type: "recommendation", providerRecommended: "Dr. Ong Boon Huat", interventionType: "teleconsult_suggestion" },
  { id: "evt-096", memberId: "mem-013", timestamp: "2026-04-08T15:30:00Z", type: "acceptance", providerRecommended: "Dr. Ong Boon Huat", providerChosen: "Dr. Ong Boon Huat", costDifferential: 0, interventionType: "teleconsult_suggestion" },
  { id: "evt-097", memberId: "mem-013", timestamp: "2026-03-22T10:00:00Z", type: "recommendation", providerRecommended: "Dr. Mohd Hafiz", interventionType: "pre_booking", notes: "Mental health GP referral" },
  { id: "evt-098", memberId: "mem-013", timestamp: "2026-03-22T10:20:00Z", type: "acceptance", providerRecommended: "Dr. Mohd Hafiz", providerChosen: "Dr. Mohd Hafiz", costDifferential: 0, interventionType: "pre_booking" },

  // mem-014 — Ismail (moderate, orthopedic) — 4 events
  { id: "evt-099", memberId: "mem-014", timestamp: "2026-04-06T09:00:00Z", type: "recommendation", providerRecommended: "Dr. Tan Chee Keong", interventionType: "pre_booking" },
  { id: "evt-100", memberId: "mem-014", timestamp: "2026-04-06T09:15:00Z", type: "acceptance", providerRecommended: "Dr. Tan Chee Keong", providerChosen: "Dr. Tan Chee Keong", costDifferential: 0, interventionType: "pre_booking" },
  { id: "evt-101", memberId: "mem-014", timestamp: "2026-03-20T14:00:00Z", type: "recommendation", providerRecommended: "Dr. Tan Chee Keong", interventionType: "cost_comparison" },
  { id: "evt-102", memberId: "mem-014", timestamp: "2026-03-20T14:30:00Z", type: "override", providerRecommended: "Dr. Tan Chee Keong", providerChosen: "Dr. Azman Shah", costDifferential: -400, interventionType: "cost_comparison" },

  // mem-024 — Tan Bee Lan (high, cancer) — 5 events
  { id: "evt-103", memberId: "mem-024", timestamp: "2026-04-12T14:00:00Z", type: "recommendation", providerRecommended: "Dr. Priya Nair", interventionType: "pre_booking" },
  { id: "evt-104", memberId: "mem-024", timestamp: "2026-04-12T14:05:00Z", type: "acceptance", providerRecommended: "Dr. Priya Nair", providerChosen: "Dr. Priya Nair", costDifferential: 0, interventionType: "pre_booking" },
  { id: "evt-105", memberId: "mem-024", timestamp: "2026-03-28T10:00:00Z", type: "recommendation", providerRecommended: "Dr. Priya Nair", interventionType: "follow_up_compliance" },
  { id: "evt-106", memberId: "mem-024", timestamp: "2026-03-28T10:20:00Z", type: "acceptance", providerRecommended: "Dr. Priya Nair", providerChosen: "Dr. Priya Nair", costDifferential: 0, interventionType: "follow_up_compliance" },
  { id: "evt-107", memberId: "mem-024", timestamp: "2026-03-15T09:00:00Z", type: "navigator_call", notes: "Navigator coordinated oncology follow-up schedule" },

  // mem-026 — Chew Mei Fong (high, cardiac+mental health) — 5 events
  { id: "evt-108", memberId: "mem-026", timestamp: "2026-04-06T08:00:00Z", type: "recommendation", providerRecommended: "Dr. Ahmad Razak", interventionType: "pre_booking" },
  { id: "evt-109", memberId: "mem-026", timestamp: "2026-04-06T08:20:00Z", type: "override", providerRecommended: "Dr. Ahmad Razak", providerChosen: "Dr. Chong Mei Fong", costDifferential: -600, interventionType: "pre_booking" },
  { id: "evt-110", memberId: "mem-026", timestamp: "2026-03-28T11:00:00Z", type: "recommendation", providerRecommended: "Dr. Mohd Hafiz", interventionType: "fragmentation_alert", notes: "Mental health consolidation" },
  { id: "evt-111", memberId: "mem-026", timestamp: "2026-03-28T11:30:00Z", type: "acceptance", providerRecommended: "Dr. Mohd Hafiz", providerChosen: "Dr. Mohd Hafiz", costDifferential: 0, interventionType: "fragmentation_alert" },
  { id: "evt-112", memberId: "mem-026", timestamp: "2026-03-20T14:00:00Z", type: "navigator_call", notes: "Navigator discussed cardiac-mental health coordination pathway" },

  // mem-015 — Yap Sook Yee (moderate, diabetes) — 4 events
  { id: "evt-113", memberId: "mem-015", timestamp: "2026-04-06T10:00:00Z", type: "recommendation", providerRecommended: "Dr. Lim Wei Ling", interventionType: "cost_comparison" },
  { id: "evt-114", memberId: "mem-015", timestamp: "2026-04-06T10:15:00Z", type: "override", providerRecommended: "Dr. Lim Wei Ling", providerChosen: "Dr. Yap Kok Seng", costDifferential: -400, interventionType: "cost_comparison", notes: "Prefers Kuching provider" },
  { id: "evt-115", memberId: "mem-015", timestamp: "2026-03-22T09:00:00Z", type: "recommendation", providerRecommended: "Dr. Lim Wei Ling", interventionType: "pre_booking" },
  { id: "evt-116", memberId: "mem-015", timestamp: "2026-03-22T09:20:00Z", type: "override", providerRecommended: "Dr. Lim Wei Ling", providerChosen: "Dr. Yap Kok Seng", costDifferential: -400, interventionType: "pre_booking" },

  // mem-017 — Saravanan (moderate, COPD) — 5 events
  { id: "evt-117", memberId: "mem-017", timestamp: "2026-04-05T09:00:00Z", type: "recommendation", providerRecommended: "Dr. Rajan Krishnan", interventionType: "pre_booking" },
  { id: "evt-118", memberId: "mem-017", timestamp: "2026-04-05T09:20:00Z", type: "override", providerRecommended: "Dr. Rajan Krishnan", providerChosen: "Dr. Harith Iskandar", costDifferential: -500, interventionType: "pre_booking" },
  { id: "evt-119", memberId: "mem-017", timestamp: "2026-03-25T10:00:00Z", type: "recommendation", providerRecommended: "Dr. Rajan Krishnan", interventionType: "follow_up_compliance" },
  { id: "evt-120", memberId: "mem-017", timestamp: "2026-03-25T10:30:00Z", type: "acceptance", providerRecommended: "Dr. Rajan Krishnan", providerChosen: "Dr. Rajan Krishnan", costDifferential: 0, interventionType: "follow_up_compliance" },
  { id: "evt-121", memberId: "mem-017", timestamp: "2026-03-15T08:00:00Z", type: "navigator_call", notes: "COPD management plan review with navigator" },

  // mem-001 — Tan Mei Ling (low, asthma) — 2 events
  { id: "evt-122", memberId: "mem-001", timestamp: "2026-04-09T09:00:00Z", type: "recommendation", providerRecommended: "Dr. Ong Boon Huat", interventionType: "follow_up_compliance" },
  { id: "evt-123", memberId: "mem-001", timestamp: "2026-04-09T09:10:00Z", type: "acceptance", providerRecommended: "Dr. Ong Boon Huat", providerChosen: "Dr. Ong Boon Huat", costDifferential: 0, interventionType: "follow_up_compliance" },

  // mem-003 — Liew Siew Peng (low, hypertension) — 2 events
  { id: "evt-124", memberId: "mem-003", timestamp: "2026-04-04T11:00:00Z", type: "recommendation", providerRecommended: "Dr. Ahmad Razak", interventionType: "pre_booking" },
  { id: "evt-125", memberId: "mem-003", timestamp: "2026-04-04T11:20:00Z", type: "override", providerRecommended: "Dr. Ahmad Razak", providerChosen: "Dr. Chong Mei Fong", costDifferential: -600, interventionType: "pre_booking", notes: "Prefers Ipoh — closer to home" },

  // mem-016 — Mohd Rizal (moderate, hypertension) — 3 events
  { id: "evt-126", memberId: "mem-016", timestamp: "2026-04-12T08:00:00Z", type: "recommendation", providerRecommended: "Dr. Ahmad Razak", interventionType: "pre_booking" },
  { id: "evt-127", memberId: "mem-016", timestamp: "2026-04-12T08:10:00Z", type: "acceptance", providerRecommended: "Dr. Ahmad Razak", providerChosen: "Dr. Ahmad Razak", costDifferential: 0, interventionType: "pre_booking" },
  { id: "evt-128", memberId: "mem-016", timestamp: "2026-03-28T14:00:00Z", type: "recommendation", providerRecommended: "Dr. Ahmad Razak", interventionType: "benefits_reminder", notes: "Benefits utilisation reminder sent" },

  // mem-018 — Nur Ain (moderate, mental health) — 3 events
  { id: "evt-129", memberId: "mem-018", timestamp: "2026-04-11T14:00:00Z", type: "recommendation", providerRecommended: "Dr. Mohd Hafiz", interventionType: "teleconsult_suggestion" },
  { id: "evt-130", memberId: "mem-018", timestamp: "2026-04-11T14:15:00Z", type: "acceptance", providerRecommended: "Dr. Mohd Hafiz", providerChosen: "Dr. Mohd Hafiz", costDifferential: 0, interventionType: "teleconsult_suggestion" },
  { id: "evt-131", memberId: "mem-018", timestamp: "2026-03-30T10:00:00Z", type: "navigator_call", notes: "Navigator check-in — mental health treatment progress" },

  // mem-008 — Chong Wei Keat (low, hypertension) — 2 events
  { id: "evt-132", memberId: "mem-008", timestamp: "2026-04-10T15:00:00Z", type: "recommendation", providerRecommended: "Dr. Ahmad Razak", interventionType: "follow_up_compliance" },
  { id: "evt-133", memberId: "mem-008", timestamp: "2026-04-10T15:10:00Z", type: "acceptance", providerRecommended: "Dr. Ahmad Razak", providerChosen: "Dr. Ahmad Razak", costDifferential: 0, interventionType: "follow_up_compliance" },

  // mem-006 — Ong Kai Wen (low, asthma) — 2 events
  { id: "evt-134", memberId: "mem-006", timestamp: "2026-04-08T08:00:00Z", type: "recommendation", providerRecommended: "Dr. Rajan Krishnan", interventionType: "cost_comparison" },
  { id: "evt-135", memberId: "mem-006", timestamp: "2026-04-08T08:30:00Z", type: "override", providerRecommended: "Dr. Rajan Krishnan", providerChosen: "Dr. Harith Iskandar", costDifferential: -500, interventionType: "cost_comparison", notes: "Prefers Ipoh provider" },
];

// ── Exclusions (10) ──

export const MOCK_EXCLUSIONS: MemberExclusion[] = [
  {
    id: "excl-001",
    memberId: "mem-019",
    type: "doctor_preference",
    providerId: "prov-020",
    providerName: "Dr. Chen Wei Ming",
    reason: "Long-standing doctor-patient relationship since 2018. Patient unwilling to switch cardiac provider.",
    expiresAt: null,
    createdAt: "2026-02-15T10:00:00Z",
  },
  {
    id: "excl-002",
    memberId: "mem-023",
    type: "doctor_preference",
    providerId: "prov-010",
    providerName: "Dr. Chong Mei Fong",
    reason: "Family doctor for all cardiac matters. Patient and spouse both see Dr. Chong.",
    expiresAt: null,
    createdAt: "2026-01-20T09:00:00Z",
  },
  {
    id: "excl-003",
    memberId: "mem-020",
    type: "active_referral",
    providerId: "prov-018",
    providerName: "Dr. Tan Soo Lin",
    reason: "Active oncology referral from hospital-based specialist. Treatment cycle in progress.",
    expiresAt: "2026-06-30T23:59:59Z",
    createdAt: "2026-03-01T08:00:00Z",
  },
  {
    id: "excl-004",
    memberId: "mem-027",
    type: "care_plan",
    providerId: "prov-020",
    providerName: "Dr. Chen Wei Ming",
    reason: "Multi-disciplinary care plan includes Dr. Chen for cardiac monitoring. Approved by care manager.",
    expiresAt: "2026-09-30T23:59:59Z",
    createdAt: "2026-03-22T14:00:00Z",
  },
  {
    id: "excl-005",
    memberId: "mem-028",
    type: "active_referral",
    providerId: "prov-003",
    providerName: "Dr. Priya Nair",
    reason: "Ongoing chemotherapy treatment — must not disrupt provider continuity.",
    expiresAt: "2026-08-31T23:59:59Z",
    createdAt: "2026-02-10T10:00:00Z",
  },
  {
    id: "excl-006",
    memberId: "mem-030",
    type: "care_plan",
    providerId: "prov-018",
    providerName: "Dr. Tan Soo Lin",
    reason: "Cancer treatment plan with Penang-based oncologist. Family support system in Penang.",
    expiresAt: "2026-07-31T23:59:59Z",
    createdAt: "2026-03-10T08:30:00Z",
  },
  {
    id: "excl-007",
    memberId: "mem-015",
    type: "doctor_preference",
    providerId: "prov-023",
    providerName: "Dr. Yap Kok Seng",
    reason: "Patient relocated to Kuching. Prefers local endocrinologist despite lower tier.",
    expiresAt: null,
    createdAt: "2026-02-01T09:00:00Z",
  },
  {
    id: "excl-008",
    memberId: "mem-029",
    type: "care_plan",
    providerId: "prov-004",
    providerName: "Dr. Tan Chee Keong",
    reason: "Post-surgery rehabilitation plan with Dr. Tan's physiotherapy team in Penang.",
    expiresAt: "2026-07-15T23:59:59Z",
    createdAt: "2026-03-05T11:00:00Z",
  },
  {
    id: "excl-009",
    memberId: "mem-010",
    type: "doctor_preference",
    providerId: "prov-020",
    providerName: "Dr. Chen Wei Ming",
    reason: "Patient has been seeing Dr. Chen for 10+ years. Strong trust relationship.",
    expiresAt: null,
    createdAt: "2026-01-10T10:00:00Z",
  },
  {
    id: "excl-010",
    memberId: "mem-025",
    type: "active_referral",
    providerId: "prov-011",
    providerName: "Dr. Ganesh Kumar",
    reason: "Specialist referral for diabetes complications. Active treatment in Melaka.",
    expiresAt: "2026-05-31T23:59:59Z",
    createdAt: "2026-03-15T09:00:00Z",
  },
];
